"""Add missing jsonb state fields

Revision ID: 0346253e69dc
Revises: 4beceecf2bbc
Create Date: 2026-08-13 09:24:17.529539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0346253e69dc'
down_revision: Union[str, None] = '4beceecf2bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('agent_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('research_jobs', sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('research_jobs', sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('research_jobs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_jobs', 'meta_data')
    op.drop_column('research_jobs', 'logs')
    op.drop_column('research_jobs', 'claims')
    op.drop_column('research_jobs', 'agent_status')
    # ### end Alembic commands ###
